### ISSUE TITLE
Uncaught TypeError: Cannot read property 'activeEditor' of undefined

### ISSUE THREAD

**Issue by ashrashr** [Five-great/tinymce-plugins#10]
大佬你好，importword 导入word后报错，tinymce版本是5.71

![image](https://user-images.githubusercontent.com/18351443/112953316-f69fd780-916f-11eb-80f7-75fa34e544b8.png)
![image](https://user-images.githubusercontent.com/18351443/112953376-04edf380-9170-11eb-9eec-05040fc9231d.png)

**Comment by Five-great** [comment]
确认一下 是否配置了相关回调函数， 加q985540932
