### ISSUE TITLE
导入work插件

### ISSUE THREAD

**Issue by tinoyet** [Five-great/tinymce-plugins#13]
你好，请问这个导入work插件要怎样设置才可以不清除work格式，尽量保持work文档原有的格式

**Comment by Five-great** [comment]
要想保留原样的 目前是不行的，本身word  和html就达不到完全一致，语法规则也不尽相同。目前只保留dom 结构 ，节约性能，不支持保留格式

**Comment by tinoyet** [comment]
那有没其他方法可以大致保留格式？用powerpaste，文本格式可以保留，但是不知道为什么图片粘贴不进去的。。有img标签，宽度高度都有就是没了src

**Comment by Five-great** [comment]
精力和时间有限 目前 没方法 有方法 我就更新了 ， powerpaste  图片是因为浏览器安全机制的原因。

**Comment by tinoyet** [comment]
好的，谢谢
