### ISSUE TITLE
importword 导入成功后报错

### ISSUE THREAD

**Issue by henggedaren** [Five-great/tinymce-plugins#21]
![QQ截图20210926001029](https://user-images.githubusercontent.com/37524430/134778231-20ee70c5-d22d-4702-8e1a-da623bf96c0f.png)

如图。

**Comment by Five-great** [comment]
layui 还是撒

**Comment by henggedaren** [comment]
> layui 还是撒

不是 就是正常html引入。

**Comment by Five-great** [comment]
那就看看你的配置
还有是不是最新的 你可以看看demo tinymce 得5.2.x以上

**Comment by dltjiangfeipeng** [comment]
请问你解决了么 我也遇到了这个问题 普通的html

**Comment by Five-great** [comment]
加我qq 985540932

**Comment by Five-great** [comment]
出现以上问题 原因是 使用了如layui 等框架 造成层级出问题， 请替换 修复版本 https://github.com/Five-great/tinymce-plugins/tree/main/importword  得插件
