### ISSUE TITLE
百度地图在https下使用有问题。

### ISSUE THREAD

**Issue by imic07** [Five-great/tinymce-plugins#3]
我们的项目地址是https， 这种情况下使用tinymce的bdmap插件有问题。
会报错，就算将http提升为https,仍然有部分图片显示不正常:
<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
![image](https://user-images.githubusercontent.com/16321067/103326590-0124d500-4a8c-11eb-98d0-05a8ebf14cdb.png)

**Comment by Five-great** [comment]
加我qq 985540932

**Comment by Five-great** [comment]
已经更改修复，因为我插件里面 含有 http 的请求 ，百度插件我没有整理出来，要用百度插件 需要同时使用 我项目的魔改media插件

**Comment by Five-great** [comment]
等一会 百度api 又改接口了

**Comment by Five-great** [comment]
已经修复了

**Comment by Five-great** [comment]
感谢反馈
