### ISSUE TITLE
使用tpImportword时，word中图片base64格式为text/plain，而不是一般的image/jpeg这种类型

### ISSUE THREAD

**Issue by hx991024** [Five-great/tinymce-plugins#39]
这个是我在项目中的图片属性 是text/plain
![image](https://user-images.githubusercontent.com/57828100/231432348-ca1da340-f66d-472d-8526-14a43e1a9145.png)

下面这个是在您demo页面同一张图片的属性 是image/jpeg
![image](https://user-images.githubusercontent.com/57828100/231432292-ed2028ac-0d80-4ac5-a735-36507b1b65d1.png)
是在 样例-基础样例 模块下

想了解一下该怎么配置

----------------------------

试了试重构前的 importword 图片类型是对的，样式是乱的

**Comment by Five-great** [comment]
这个需要配置 一个属性&nbsp; tinymce 自动将图片转为服务器地址









      发自我的企业微信         

 
 
 ----------回复的邮件信息----------
 ***@***.***&gt; 于2023年4月12日(周三) 晚上6:39写道:

  

 
这个是我在项目中的图片属性 是text/plain
 
 
下面这个是在您demo页面同一张图片的属性 是image/jpeg
 
 是在 样例-基础样例 模块下
 
想了解一下该怎么配置

**Comment by hx991024** [comment]
@Five-great 
tpimportword这个blob中的type不是图片应该有的类型
![image](https://user-images.githubusercontent.com/57828100/231457759-b480464e-250c-4e63-be40-e9357b47fe21.png)

请问能不能像原来的importword的一样，显示出图片真正的类型
![image](https://user-images.githubusercontent.com/57828100/231460477-826d913f-a911-46b4-9313-d1460630f89d.png)

**Comment by xsq810** [comment]
@WingLeoo 请问一下你解决了吗，我也是同样的问题，不知道怎么解决。

**Comment by hx991024** [comment]
> @WingLeoo 请问一下你解决了吗，我也是同样的问题，不知道怎么解决。
并没有解决，我自己在 images_upload_handler 方法中做了统一处理
![image](https://github.com/Five-great/tinymce-plugins/assets/57828100/6022a811-fcf2-4c39-af36-203e14d0f336)
使用tinymce上传的图片正常处理，使用word插件上传的类型统一封装成png了

**Comment by xsq810** [comment]
@WingLeoo 不好意思再打扰您一下，请问您的 uploadImage 是自己重写的上传图片方法吗，可以参考一下吗，我这边这样写会有问题
![image](https://github.com/Five-great/tinymce-plugins/assets/80967180/89825ba3-9488-43ee-b02e-18531a175a8d)

**Comment by hx991024** [comment]
> @WingLeoo 不好意思再打扰您一下，请问您的 uploadImage 是自己重写的上传图片方法吗，可以参考一下吗，我这边这样写会有问题 ![image](https://user-images.githubusercontent.com/80967180/257987740-89825ba3-9488-43ee-b02e-18531a175a8d.png)

![image](https://github.com/Five-great/tinymce-plugins/assets/57828100/6475ed0c-5c60-4d5f-bf73-92d84742cf35)
这个后缀是 .png 吧 你写的是 png

**Comment by Five-great** [comment]
进qq群 143085779  里面最新的 tpimportword 直接调用 tinymce官方 图片上传回调 @xsq810

**Comment by xsq810** [comment]
@WingLeoo 非常感谢您！实在是太感谢了！现在解决了，老是犯这种低级错误，太不应该了，今后会注意点的。

**Comment by xsq810** [comment]
@Five-great 好的我去看看，感谢你！
