### ISSUE TITLE
关于letterspacing插件

### ISSUE THREAD

**Issue by zjhr** [Five-great/tinymce-plugins#6]
letterspacing插件感觉怪怪的，比如我选择一段文字后，使用letterspacing格式化，然后在这段文字后面写文字，他还会有letterspacing的效果。希望可以改进 @Five-great

**Comment by Five-great** [comment]
你这情况的，应该是操作步骤的问题，  因为 letter-spacing 为行内样式 ，所以应用后，只能在当前行类内样式（比如 <span>）中有效，和 font-size  等是一样的，如果 将 letter-spacing 应用块级元素的块级样式，当前段 都会有 letter-spacing 效果。 但是在更多应用场景，比如 中英文 数字 都有的段落，需要  letter-spacing 为行内样式更合适，（比如： importword 导入word插件。可以直接导入word ,并且保证word中图片不会丢失，自动转为base64），如果 letter-spacing 此时块级元素的块级样式，那么 英文单词就字母之间的间距就与汉字间距相同。所以根据标准来讲 目前是较为合适的

**Comment by Five-great** [comment]
一般调 字间距， 文字大小 之类的操作 ，一般习惯 完成文字编辑 ，再去调样式

**Comment by zjhr** [comment]
好吧，其实我希望可以做到像官方的大B效果就最好了

**Comment by zjhr** [comment]
意思就是选中哪段文字就只是格式化那一段文字，而不是整行的文字格式化

**Comment by Five-great** [comment]
http://fivecc.gitee.io/tinymce-plugins/demo/
现在就是这样
dome 问题 ，才改了 插件是之前就改了

**Comment by Five-great** [comment]
下载最新的插件 替换一下

**Comment by Five-great** [comment]
之前 的确是这样 修复过来了

**Comment by zjhr** [comment]
@Five-great 噢噢，好的，我等一下试试，那个格式化时候，没加入回撤队列也修复了吗

**Comment by Five-great** [comment]
是layout 那个么 插件么

**Comment by zjhr** [comment]
letterspacing插件，之前是格式化后没有加入回撤队列

**Comment by Five-great** [comment]
那个和行高 一样 ， 回撤 是回撤到默认转态么， 选错了 再次选择就是哈

**Comment by zjhr** [comment]
@Five-great 下载了最新的，发现完美了，😁，没有以上问题

**Comment by Five-great** [comment]
不像 首行缩进， 就两个状态 ，点一下应用 点一下回撤， 字间距 多个状态， 除非多加一个按钮

**Comment by zjhr** [comment]
@Five-great 哦。。不对，还是没有加入回撤队列🙄️

**Comment by Five-great** [comment]
字间距 和行高  字号 一样没有回撤的，ctrl + z 算么

**Comment by zjhr** [comment]
目前情况是这样的，你输入一段文字后，用letterspacing格式化，正常情况是，我按回撤健，应该是还原到没格式化的文字格式，再按回撤健，文字没有。但是实际情况是，按回撤健，直接没有了文字

**Comment by Five-great** [comment]
额额  改变字号 行高 有回撤么

**Comment by zjhr** [comment]
> 字间距和行高字号一样没有回撤的，ctrl + z算么



> 额额 改变字号 行高 有回撤么

有的哦

**Comment by zjhr** [comment]
你可以试试😁

**Comment by Five-great** [comment]
额 不知道 你说的那个键 BACK

**Comment by Five-great** [comment]
加我qq 985540932

**Comment by zjhr** [comment]
> 额 不知道 你说的那个键 BACK

就是ctrl + z或者编辑器的回撤按键

**Comment by Five-great** [comment]
ctrl + z  和编辑器回撤 可以啊

**Comment by Five-great** [comment]
你看我demo

**Comment by Five-great** [comment]
那个 不是插件里面写， 浏览器的机制啊 跟插件无关

**Comment by zjhr** [comment]
> 目前情况是这样的，你输入一段文字后，用letterspacing格式化，正常情况是，我按回撤健，应该是还原到没格式化的文字格式，再按回撤健，文字没有。但是实际情况是，按回撤健，直接没有了文字

额。。。还是目前的情况

**Comment by Five-great** [comment]
我没遇到这锅问题额

**Comment by zjhr** [comment]
> 那个 不是插件里面写， 浏览器的机制啊 跟插件无关

不是浏览器的机制的😷。。。

**Comment by Five-great** [comment]
@zjhr  相关插件已更新 layout  letterspacing indent2em lineheight    https://github.com/Five-great/tinymce-plugins/releases/tag/0.0.5

**Comment by Five-great** [comment]
ctrl + z或者编辑器的回撤 已解决
