### ISSUE TITLE
importword使用报错

### ISSUE THREAD

**Issue by swwios12369** [Five-great/tinymce-plugins#7]
我将插件集成到vue项目中，选择完docx文件后，浏览器控制台报错，uncaught referenceError：mammoth is not defined，页面停留在正在转换中

**Comment by Five-great** [comment]
此问题 目前 已解决，可下载最新版插件

**Comment by swwios12369** [comment]
最新版插件已可以导入word文件，不需要手动创建index.js

**Comment by swwios12369** [comment]
vue 导入docx文件后，部分样式丢失，比如标题居中。

**Comment by Five-great** [comment]
目前只保留图片 和 dom 结构以及文本类容，暂未支持css样式
